### PR TITLE
Add download website and all sub-webpages and directories option

### PR DESCRIPTION
**Pull request by rsnk96**
Can be very useful for downloading tutorial webpages, etc for later reference

### CODE REVIEW

**Comment by roytenberg** [comment]
Ahh, I was waiting for the first wget commit. Can you change it to curl? I don't want to start a holy war, but I just prefer curl :+1:

**Comment by rsnk96** [comment]
Haha :smile: 

I prefer curl too. It's more cross-platform and supports ftp, etc, But I'm afraid this is one task that wget has better support for than curl does. Refer: [here](http://superuser.com/a/705827)

**Comment by rsnk96** [comment]
Added additional commands to easily start a server in the current directory in the local server

**Comment by roytenberg** [comment]
So, sorry I just got to this. wget is actually pretty sweet. Is the user agent argument necessary? Also, I couldn't find the robots section in the manpages from a quick grep; care to explain it?

**Comment by rsnk96** [comment]
a robots.txt could modify the way wget functions, for instance check [here](https://github.com/Creare/magento-robots/blob/master/robots.txt)

User agent as mozilla simply because most websites allow Mozilla to view it :)

**Comment by roytenberg** [comment]
Hey Nikhil, I finally got a chance to peep these commits. Everything checks out and is awesome, but I've split up .bashrc and .bash_aliases, per one of the now-closed issues. Could you do the same, and move these commits to .bash_aliases? Resolving the conflicts is a huge pain in the butt. Thanks 👍

**Comment by rsnk96** [comment]
Hi Roytenberg. I've merged the changes and made the shift.
P.S. using `git mergetool`
can make merging a lot easier :)

**Pull request merged**
