### PR TITLE
add incognito mode

### PR DESCRIPTION
**Pull request by mdibaiee**
:+1: :grin:

### CODE REVIEW

**Comment by snood1205** [comment]
From just a practical standpoint, if this is .bashrc, then it would only be read by bash, so wouldn't the only shell that need be supported, be bash?

**Comment by mdibaiee** [comment]
@snood1205 well then I propose we use more than just `.bashrc`, because that means we are excluding a lot of `zsh` and other shell users. I personally use zsh and I just copied the parts I liked from the file in the repository to my own `.zshrc`

**Comment by Phrohdoh** [comment]
That is what oh-my-zsh is for.

**Comment by mdibaiee** [comment]
I don't see your point, though I don't see why someone couldn't do `source ~/.bashrc` at the end/beginning of their shell's rc file.

**Comment by roytenberg** [comment]
Well guys, this IS a bash specific repo. 

Regardless, going to merge this, and trim it down significantly to get rid of the shell checks. I don't want you to lose out on a successful PR :1st_place_medal:

**Pull request merged**
